#!/bin/bash

if [ ! -d /usr/share/gooroom/locale/ko/LC_MESSAGES ];then
  mkdir -p /usr/share/gooroom/locale/ko/LC_MESSAGES
  fi

  msgfmt ./po/ko.po \
    -o /usr/share/gooroom/locale/ko/LC_MESSAGES/gooroom-usbctl.mo
